# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options

BASE_URL = "http://127.0.0.1:5500/teton/1.6"


class TestSmoke:
    def setup_method(self, method):
        options = Options()
        options.add_argument("--headless=new")
        self.driver = webdriver.Chrome(options=options)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_1_logo_header_and_title(self):
        """Test #1 - Logo Header and Title"""
        self.driver.get(f"{BASE_URL}/index.html")
        self.driver.set_window_size(1550, 830)
        elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
        assert len(elements) > 0
        assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").text == "Teton Idaho"
        assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h2").text == "Chamber of Commerce"
        assert self.driver.title == "Teton Idaho CoC"

    def test_2_home_page_spotlights_and_join_feature(self):
        """Test #2 - Home Page - Spotlights and Join Feature"""
        self.driver.get(f"{BASE_URL}/index.html")
        self.driver.set_window_size(1550, 830)
        elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight1 > .centered-image")
        assert len(elements) > 0
        elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight2 > .centered-image")
        assert len(elements) > 0
        elements = self.driver.find_elements(By.LINK_TEXT, "Join Us")
        assert len(elements) > 0
        self.driver.find_element(By.LINK_TEXT, "Join Us").click()
        elements = self.driver.find_elements(By.LINK_TEXT, "Join")
        assert len(elements) > 0

    def test_3_directory_grid_and_list_feature(self):
        """Test #3 - Directory Grid and List feature"""
        self.driver.get(f"{BASE_URL}/index.html")
        self.driver.set_window_size(1550, 830)
        self.driver.find_element(By.LINK_TEXT, "Directory").click()
        self.driver.find_element(By.ID, "directory-list").click()
        self.driver.find_element(By.ID, "directory-grid").click()
        assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"
        self.driver.find_element(By.ID, "directory-list").click()
        assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"

    def test_4_join_page_data_entry(self):
        """Test #4 - Join Page Data Entry"""
        self.driver.get(f"{BASE_URL}/join.html")
        self.driver.set_window_size(1550, 830)
        elements = self.driver.find_elements(By.NAME, "fname")
        assert len(elements) > 0
        self.driver.find_element(By.NAME, "fname").send_keys("Test")
        self.driver.find_element(By.NAME, "lname").send_keys("User")
        self.driver.find_element(By.NAME, "bizname").send_keys("Test Biz")
        self.driver.find_element(By.NAME, "biztitle").send_keys("Tester")
        self.driver.find_element(By.NAME, "submit").click()
        elements = self.driver.find_elements(By.NAME, "email")
        assert len(elements) > 0

    def test_5_admin_page_username_password(self):
        """Test #5 - Admin Page Username/Password"""
        self.driver.get(f"{BASE_URL}/admin.html")
        self.driver.set_window_size(1550, 830)
        elements = self.driver.find_elements(By.ID, "username")
        assert len(elements) > 0
        self.driver.find_element(By.ID, "username").send_keys("wronguser")
        self.driver.find_element(By.ID, "password").send_keys("wrongpass")
        self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()
        assert self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").text == "Invalid username and password."
